const PROMISE = "PROMISE";
const PENDING = "PENDING";
const RESOLVED = "RESOLVED";
const REJECTED = "REJECTED";
const CURRENT_LOCATION ="CURRENT_LOCATION"

export {
    PROMISE,
    PENDING,
    RESOLVED,
    REJECTED,
    CURRENT_LOCATION
}